### ISSUE TITLE
TypeError on incorrect option input in kanji multichoice mode

### ISSUE THREAD

**Issue by mihhailko** [mihhailko/kac#1]
```
い
い
<
魂(1)勇(2)六(3)緩(4)値(5)恐(6)憤(7)背(8)位(9)忙(10)悼(11)彩(12)貧(13)詳(14)易(15)早(16)冷(17)芳(18)堅(19)清(20)弱(21)美(22)慌(23)明(24)粗(25)寒(26)激(27)鈍(28)小(29)遠(30)慈(31)危(32)太(33)恭(34)細(35)暗(36)貴(37)戒(38)柔(39)問(40)今(41)麗(42)速(43)泉(44)灰(45)板(46)互(47)傷(48)忌(49)固(50)紛(51)惜(52)多(53)甘(54)賢(55)犬(56)強(57)岩(58)舞(59)暖(60)新(61)率(62)珍(63)丸(64)長(65)否(66)偉(67)親(68)眠(69)言(70)急(71)鋭(72)永(73)良(74)貝(75)亡(76)怒(77)優(78)費(79)五(80)正(81)恨(82)境(83)間(84)等(85)重(86)居(87)池(88)基(89)礎(90)至(91)憂(92)熱(93)深(94)硬(95)淡(96)大(97)要(98)頂(99)酸(100)色(101)濃(102)幼(103)短(104)家(105)厚(106)用(107)白(108)辛(109)射(110)報(111)薄(112)古(113)怖(114)石(115)憩(116)少(117)青(118)涼(119)災(120)近(121)煙(122)拙(123)無(124)額(125)井(126)安(127)抱(128)侍(129)痛(130)愁(131)善(132)汚(133)平(134)寂(135)苦(136)恥(137)狂(138)市(139)初(140)潔(141)欲(142)芋(143)疎(144)若(145)悲(146)怪(147)行(148)醜(149)相(150)病(151)虐(152)快(153)生(154)命(155)秀(156)乏(157)勢(158)低(159)尊(160)赤(161)軟(162)幸(163)息(164)入(165)
は
Traceback (most recent call last):
  File "./kac.py", line 257, in <module>
    main()
  File "./kac.py", line 197, in main
    bf, kl = process_kanji_choice(op, choices, mclen, buff, kanji_choices)
  File "./kac.py", line 147, in process_kanji_choice
    if ((int(selection) - 1) < len(kc)):
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
`
```

**Comment by mihhailko** [comment]
Solved.
