### ISSUE TITLE
IndexError when typing x in multichoice mode

### ISSUE THREAD

**Issue by mihhailko** [mihhailko/kac#10]
`Traceback (most recent call last):
  File "./kac.py", line 230, in <module>
    main()
  File "./kac.py", line 207, in main
    cbuf.remove_last()
  File "/home/nurk/devproj/python/kac-proj/cbuffer.py", line 34, in remove_last
    self.data.pop()
IndexError: pop from empty list
`

**Comment by mihhailko** [comment]
Solved.
